spring:
  profiles: test
  application:
    name: demo
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  datasource:
    url: jdbc:mysql://119.3.23.16:3306/xunda_test?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  mvc:
    view:
      suffix: .html
  thymeleaf:
    prefix: classpath:/static/
  redis:
    database: 0
    host: 123.60.0.152
    port: 6379
    password: xunda123
    timeout: 1000
    jedis:
      pool:
        max-active: 100
        max-idle: 3
        max-wait: -1
        min-idle: 0
  # 文件上传路径
  profile: /root/nginx/html/files
  #  图片域名
  imgUrl: http://123.60.0.152:8085/files

server:
  port: 8088

mybatis-plus:
  # 搜索指定包别名
  type-aliases-package: com.xunda.im.dao
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapper-locations: classpath:mapper/*.xml
  # 加载全局的配置文件
  #  config-location: classpath:/mybatis/mybatis-config.xml
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    #logic-delete-value: 1
    #logic-not-delete-value: 0
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'

plumelog:
  appName: demo
  redisHost: 119.3.23.16:6379
  redisAuth: pwd

#华为obs配置
obs:
  endPoint: obs.cn-east-3.myhuaweicloud.com #每个区域一个
  bucketName: ahxd #桶名，可以在华为云控制台添加，可以有多个
  ak: IP3GPV0JTU2VPFT8MCQ7
  sk: 3qDRxizVN8ukaMfPPpqtvprzr34TEx7BpwhM1jhC
  bucketLocation: cn-east-3

rsa:
  enabled: true
  scan-annotation: true
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvL1DtPruTPBm5ZasOJ+FMl/VHx3b3Bjuq0IdfNkM+TK6kwJmiU2EyIlUPwEIm3zI1+N7Fl6Ykr8hspDfn2iBG0HSNpZAz8wp73DALOSBLYWBPn0PQXY9j89L0bF2r9ygZXP++jXkv9i6c25jqyEzQzpU0MDCiVuGNo10Q+NT6BtBx9U2zj/tztks5dkT1BPAqVO0WKospAUFHSSoJAadx4yaFiwtFt2M1FWCr/iDjYAI1dq+ade6vcj+0qjyPoFkpuzs7C53JU7Qvfj3jf+D7LG6hVROFi3OB5K2+r/pXQcvLXvwgIgHl1yYp56YqfxEQ2pNzPCM2Oa67Lw+Fj9/OQIDAQAB
  privateKey: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC8vUO0+u5M8Gbllqw4n4UyX9UfHdvcGO6rQh182Qz5MrqTAmaJTYTIiVQ/AQibfMjX43sWXpiSvyGykN+faIEbQdI2lkDPzCnvcMAs5IEthYE+fQ9Bdj2Pz0vRsXav3KBlc/76NeS/2LpzbmOrITNDOlTQwMKJW4Y2jXRD41PoG0HH1TbOP+3O2Szl2RPUE8CpU7RYqiykBQUdJKgkBp3HjJoWLC0W3YzUVYKv+IONgAjV2r5p17q9yP7SqPI+gWSm7OzsLnclTtC9+PeN/4PssbqFVE4WLc4Hkrb6v+ldBy8te/CAiAeXXJinnpip/ERDak3M8IzY5rrsvD4WP385AgMBAAECggEAOm1cyGnl22uQbwJ1zhGT6kRAdaGIrloJiHqvJjcLDRnnKBtWIqscr/fTXK21PG0kv7BsKkCees8wX1b54x822HlH2h4pciqB0N3WoA8c7jqmB/IvBtTTufEyR3fohgiGnuGJzWthpQIytgk2UYO1mtoz52vEzUDIC5s+osV89BzzkBUBfpiXIey1ezHgI4LdQw2sNr0a/p9hHx3YZNAO7CmQB5CQH8LLxkOHyAH4xltN3Ql8egtxUMCCjsbm7Ky3i3DEQ/LgONiKAF4bf/FJ7qI09PMsSf97nixJyiSAwqRjocy1nT8UQRtKa03fBWbUslK4huFa4xdxLL8Upb7EAQKBgQDr/XUleE/zW8BIcVRt0v9IDA2UDBbOSlqOLzL46cOuvDd+Ox5r622ntu8wJNvir4wM3MfEA3AWnbNnNG9EMuASSYgExYbAeFI3+aZiEBqXLxgpT0BdfH+kgkAWdmF9VSHVHSp+S6MXelN3VBYc2DfWd9NFCiTi5vYmgX/14OZ4bQKBgQDMvidQ4u7lhZ92HzoBzCVrnljpVCFG/A8CqIGKC7gvspgvbNAUjBtbtqUiwEnXrT7VTmHMUuxX256iuy2yPXOkB0hxlJi4i/e3I+rc/IWBvQr8U3OfEkN98QiiQMGdmzZu+4TV0OXtsDihpZlP96Y4LZ3C/J00yoqR8X2tf2Y6fQKBgQCGYmb7V2/v3Se6GQ9DGwxUMsjorZmvD5hRr38PT88nCfdv4qqIOiDPiNTcTaEJjX3rNS5s6KhDuLoY4zsZUv9WapkSXolFwT7QsVGWNiVuQls36vF0SxlEzQdBw1fwzzHc8ibolJnjHL27Dh8pfdcOQl4EyqoGrA8wDj6X/eJAYQKBgQCvd4/uTG59GkWNUDnAbJrtXmnInide1IpwtsU978lMZ3zxuAmkcmbH9QIVhEJEqt8co+5A1BhlO3z67fu9s9i1jOBTJwyzrJEBzbBs76XjiIYvtb1zaI2bE8VYeLL2RZ0jBD/VlxBW4h3Gu0tnM1Cq+L0p7KE2KxcS+KnC1VphaQKBgQCJo1DcCJ5Bgg9y8M5RweqmrDau+GBCmZUJJ/32ibU2Ds6ep/HY0OV/ZbNbL0KBnKcnLRCS9uSipTQQnRLuRIlR3QyghDGtDA4RNg+DzEEs/kDBX03NBCJBFnB7GMXmXzmwzhMRRenX/37o9ry/ONDXTts9Va7Xp3P8lpV1TVTkMg==